### ISSUE TITLE
Adjusted path to selection.json not working

### ISSUE THREAD

**Issue by silversession** [viivue/acf-icomoon#12]
Trying to adjust the path in the acf field to `assets/fonts/icomoon/selection.json` or `dist/fonts/icomoon/selection.json` will result in an empty overlay (where you can actually select the icons).

**Comment by daomapsieucap** [comment]
Hi @silversession,

Could you help us provide some more information to debug the issue:
- Some screenshots about the case you've got.
- Which plugin version you've installed (could you try to update to the latest version of our plugin?)
- Some more description about the specific steps to reproduce the issue?

Just because I've tested to update selection.json on my site but it's still working, I think there is some wrong config which I would like to know exactly to fix the issue.

Thanks for supporting our plugin.

**Comment by silversession** [comment]
Hi @daomapsieucap,

* I use the newes Version of the Plugin: 4.0.7

In the acf-field there is the option to adjust the path to the json-file. It seems, that the path to the json-File is hard Coded. 

If I put the json file in assets/fonts/selection.json everything works fine - even if the path to the json file is different than the json location. If I move the the file to assets/fonts/icomoon/selection.json and adjust the path in the acf-field as well - then the icons are not found.

File under assets/fonts/icomoon/selection.json
![Bildschirmfoto 2022-09-30 um 11 52 32](https://user-images.githubusercontent.com/28433530/193244725-f91d1500-d3b3-4405-a1d0-2b6ab1977cf5.png)

Empty selection in Gutenberg Editor
![Bildschirmfoto 2022-09-30 um 11 52 21](https://user-images.githubusercontent.com/28433530/193245254-1eb85387-69b4-4744-84ae-41ebd5b38c72.png)

Path to assets/fonts/icomoon/selection.json
![Bildschirmfoto 2022-09-30 um 11 51 45](https://user-images.githubusercontent.com/28433530/193245328-18d905c3-b840-46a2-9b6e-5a8d4454cd5b.png)

If I move the file to assets/fonts/selection.json - then it works out of the box. Even if the path in the acf field is wrong...

Hope that helps?

**Comment by daomapsieucap** [comment]
Hi @silversession,

Sorry for the late reply, I tested and found the bug. The latest version fixed this issue, but there is some issue when releasing the plugin to wordpress.org.

Please try to download and install v4.0.8 here: https://github.com/viivue/acf-icomoon/releases/tag/v4.0.8.

Thanks for taking time help us to figure out the bug.

**Comment by silversession** [comment]
I just tested it. 

It works!
